import yaml
import os

# Define the paths to the submodules' YAML files
submodule_yaml_paths = [
    'docs/yamltest/docs_info.yaml'
]

# Define the output markdown file
output_md_path = 'docs/index.md'

# Initialize the markdown content
cards_md = """
---
title: "ICICLE Training Catalog"
---

<!-- This file is auto-generated by the generate_cards.py script. -->

# ICICLE Training Catalog

Welcome to the ICICLE Training Catalog! Explore our resources and training opportunities through the categories below.

"""

# Process each submodule's YAML file
for submodule_yaml_path in submodule_yaml_paths:
    if os.path.exists(submodule_yaml_path):
        with open(submodule_yaml_path, 'r') as file:
            data = yaml.safe_load(file)

        for category, items in data.items():
            cards_md += f"\n## {category}\n"
            for item in items:
                title = item.get('title', 'No Title')
                description = item.get('description', 'No Description')
                tags = item.get('tags', [])
                tags_md = ' '.join([f'<a href="#" class="tag">{tag}</a>' for tag in tags])
                cards_md += f"""
<div class="card">
  <div class="card-header">
    <h2><a href="#">{title}</a></h2>
  </div>
  <div class="card-body">
    <p>{description}</p>
    <div class="tags">
      {tags_md}
    </div>
  </div>
</div>
"""

# Write to the markdown file
with open(output_md_path, 'w') as file:
    file.write(cards_md)
